"""
RAZE Enterprise AI OS – Pydantic Schema Registry

Import all public schema classes so they can be referenced as::

    from app.schemas import ChatRequest, ChatResponse, UserResponse
"""

from app.schemas.admin import (
    AIConfigCreate,
    AIConfigListResponse,
    AIConfigResponse,
    AIConfigUpdate,
    AdminDashboard,
    DashboardChart,
    ProviderHealth,
    SystemStats,
    TopModel,
    TopTool,
    TrendPoint,
)
from app.schemas.analytics import (
    AnalyticsSummaryResponse,
    DateRangeRequest,
    MetricSeries,
    ObservabilityLogFilterRequest,
    ObservabilityLogListResponse,
    ObservabilityLogResponse,
    TimeSeriesPoint,
    UsageMetricsListResponse,
    UsageMetricsResponse,
    UsageMetricsTotals,
    UserSessionListResponse,
    UserSessionResponse,
)
from app.schemas.auth import (
    APIKeyCreate,
    APIKeyCreateResponse,
    APIKeyListResponse,
    APIKeyResponse,
    LoginRequest,
    PasswordChangeRequest,
    RefreshTokenRequest,
    TokenResponse,
    UserCreate,
    UserListResponse,
    UserResponse,
    UserUpdate,
)
from app.schemas.chat import (
    ChatRequest,
    ChatResponse,
    ConversationListResponse,
    ConversationResponse,
    ConversationUpdate,
    MessageInput,
    MessageListResponse,
    MessageResponse,
    StreamChunk,
    StreamEventType,
    ToolCallChunk,
)
from app.schemas.knowledge import (
    KnowledgeApprovalRequest,
    KnowledgeChunkListResponse,
    KnowledgeChunkResponse,
    KnowledgeSearchRequest,
    KnowledgeSearchResponse,
    KnowledgeSearchResult,
    KnowledgeSourceCreate,
    KnowledgeSourceListResponse,
    KnowledgeSourceResponse,
    KnowledgeSourceUpdate,
)
from app.schemas.memory import (
    MemoryCreate,
    MemoryListResponse,
    MemoryResponse,
    MemorySearchRequest,
    MemorySearchResponse,
    MemorySearchResult,
    MemoryUpdate,
    RetentionPolicyCreate,
    RetentionPolicyResponse,
)
from app.schemas.tool import (
    ToolCreate,
    ToolExecutionListResponse,
    ToolExecutionResponse,
    ToolListResponse,
    ToolResponse,
    ToolTestRequest,
    ToolTestResponse,
    ToolUpdate,
)

__all__ = [
    # Auth
    "LoginRequest",
    "RefreshTokenRequest",
    "TokenResponse",
    "UserCreate",
    "UserUpdate",
    "PasswordChangeRequest",
    "UserResponse",
    "UserListResponse",
    "APIKeyCreate",
    "APIKeyCreateResponse",
    "APIKeyResponse",
    "APIKeyListResponse",
    # Chat
    "MessageInput",
    "ChatRequest",
    "ChatResponse",
    "StreamChunk",
    "StreamEventType",
    "ToolCallChunk",
    "ConversationResponse",
    "ConversationUpdate",
    "ConversationListResponse",
    "MessageResponse",
    "MessageListResponse",
    # Knowledge
    "KnowledgeSourceCreate",
    "KnowledgeSourceUpdate",
    "KnowledgeSourceResponse",
    "KnowledgeSourceListResponse",
    "KnowledgeApprovalRequest",
    "KnowledgeChunkResponse",
    "KnowledgeChunkListResponse",
    "KnowledgeSearchRequest",
    "KnowledgeSearchResponse",
    "KnowledgeSearchResult",
    # Memory
    "MemoryCreate",
    "MemoryUpdate",
    "MemoryResponse",
    "MemoryListResponse",
    "MemorySearchRequest",
    "MemorySearchResponse",
    "MemorySearchResult",
    "RetentionPolicyCreate",
    "RetentionPolicyResponse",
    # Tool
    "ToolCreate",
    "ToolUpdate",
    "ToolResponse",
    "ToolListResponse",
    "ToolTestRequest",
    "ToolTestResponse",
    "ToolExecutionResponse",
    "ToolExecutionListResponse",
    # Admin
    "AIConfigCreate",
    "AIConfigUpdate",
    "AIConfigResponse",
    "AIConfigListResponse",
    "SystemStats",
    "ProviderHealth",
    "AdminDashboard",
    "DashboardChart",
    "TrendPoint",
    "TopTool",
    "TopModel",
    # Analytics
    "DateRangeRequest",
    "ObservabilityLogResponse",
    "ObservabilityLogListResponse",
    "ObservabilityLogFilterRequest",
    "UsageMetricsResponse",
    "UsageMetricsListResponse",
    "UsageMetricsTotals",
    "UserSessionResponse",
    "UserSessionListResponse",
    "AnalyticsSummaryResponse",
    "MetricSeries",
    "TimeSeriesPoint",
]
