"""
RAZE Enterprise AI OS – Database & Cache Setup

Provides:
  - Async SQLAlchemy engine with connection pooling
  - Session factory (AsyncSession)
  - Base ORM model (UUID PK, created_at, updated_at)
  - get_db() FastAPI dependency
  - Redis async client factory
"""

from __future__ import annotations

import uuid
from contextlib import asynccontextmanager
from datetime import datetime, timezone
from typing import AsyncGenerator

import structlog
from redis.asyncio import ConnectionPool, Redis
from sqlalchemy import DateTime, MetaData, func, text
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.ext.asyncio import (
    AsyncAttrs,
    AsyncEngine,
    AsyncSession,
    async_sessionmaker,
    create_async_engine,
)
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column

from app.config import settings

logger = structlog.get_logger(__name__)

# ─── SQLAlchemy Naming Convention ─────────────────────────────────────────────
# Ensures Alembic can reliably detect and auto-generate constraint names.

NAMING_CONVENTION: dict[str, str] = {
    "ix": "ix_%(column_0_label)s",
    "uq": "uq_%(table_name)s_%(column_0_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}


# ─── Async Engine ─────────────────────────────────────────────────────────────

def _build_engine() -> AsyncEngine:
    return create_async_engine(
        settings.database_url,
        pool_size=settings.database_pool_size,
        max_overflow=settings.database_max_overflow,
        pool_timeout=settings.database_pool_timeout,
        pool_recycle=settings.database_pool_recycle,
        pool_pre_ping=True,
        echo=settings.database_echo,
        future=True,
        connect_args={
            # asyncpg-specific: set statement timeout to 30 s per query
            "server_settings": {
                "statement_timeout": "30000",
                "jit": "off",  # pgvector perf: JIT hurts ANN queries
            },
        },
    )


engine: AsyncEngine = _build_engine()

# ─── Session Factory ──────────────────────────────────────────────────────────

AsyncSessionLocal: async_sessionmaker[AsyncSession] = async_sessionmaker(
    bind=engine,
    class_=AsyncSession,
    autocommit=False,
    autoflush=False,
    expire_on_commit=False,
)


# ─── Base Model ───────────────────────────────────────────────────────────────

class Base(AsyncAttrs, DeclarativeBase):
    """
    Abstract base class for all ORM models.

    Columns added to every table:
      id          – UUID primary key (server-generated by PostgreSQL)
      created_at  – timestamp with time zone, server default NOW()
      updated_at  – timestamp with time zone, kept current by a trigger
    """

    metadata = MetaData(naming_convention=NAMING_CONVENTION)

    # Subclasses must set __tablename__; all other attrs are inherited.
    __abstract__ = True

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4,
        server_default=text("gen_random_uuid()"),
        index=True,
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        nullable=False,
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        onupdate=func.now(),
        nullable=False,
    )

    def to_dict(self) -> dict:
        """Return a plain-dict representation (useful for debugging / logging)."""
        return {c.name: getattr(self, c.name) for c in self.__table__.columns}

    def __repr__(self) -> str:
        return f"<{self.__class__.__name__} id={self.id}>"


# ─── FastAPI Dependency ───────────────────────────────────────────────────────

async def get_db() -> AsyncGenerator[AsyncSession, None]:
    """
    Yield an AsyncSession per request, rolling back on error and always
    closing the session on exit.

    Usage::

        @router.get("/")
        async def handler(db: AsyncSession = Depends(get_db)):
            ...
    """
    async with AsyncSessionLocal() as session:
        try:
            yield session
            await session.commit()
        except Exception:
            await session.rollback()
            raise
        finally:
            await session.close()


@asynccontextmanager
async def get_db_context() -> AsyncGenerator[AsyncSession, None]:
    """
    Async context-manager version for use outside of FastAPI request context
    (e.g. Celery tasks, startup hooks).

    Usage::

        async with get_db_context() as db:
            result = await db.execute(...)
    """
    async with AsyncSessionLocal() as session:
        try:
            yield session
            await session.commit()
        except Exception:
            await session.rollback()
            raise
        finally:
            await session.close()


# ─── Redis Client ─────────────────────────────────────────────────────────────

_redis_pool: ConnectionPool | None = None


def _get_redis_pool() -> ConnectionPool:
    global _redis_pool
    if _redis_pool is None:
        _redis_pool = ConnectionPool.from_url(
            settings.redis_url,
            max_connections=settings.redis_max_connections,
            decode_responses=settings.redis_decode_responses,
            socket_timeout=settings.redis_socket_timeout,
            socket_connect_timeout=settings.redis_socket_connect_timeout,
        )
    return _redis_pool


def get_redis() -> Redis:
    """
    Return a Redis client backed by a shared connection pool.

    The client is not a coroutine – instantiate it wherever needed,
    then ``await`` the individual commands.

    Usage::

        redis = get_redis()
        await redis.set("key", "value", ex=300)
    """
    return Redis(connection_pool=_get_redis_pool())


async def get_redis_dep() -> AsyncGenerator[Redis, None]:
    """FastAPI dependency that yields a Redis client."""
    client = get_redis()
    try:
        yield client
    finally:
        await client.aclose()


# ─── Lifecycle Helpers ────────────────────────────────────────────────────────

async def connect_db() -> None:
    """
    Called at application startup: verify the DB connection is alive,
    create required extensions, and initialize tables if needed.
    """
    try:
        async with engine.begin() as conn:
            await conn.execute(text("SELECT 1"))
            await conn.execute(text("CREATE EXTENSION IF NOT EXISTS vector"))
            await conn.execute(text("CREATE EXTENSION IF NOT EXISTS pg_trgm"))
            await conn.execute(text("CREATE EXTENSION IF NOT EXISTS pgcrypto"))
        logger.info("database.connected", url=settings.database_url.split("@")[-1])

        # Create all tables if they don't exist
        from app.models import (  # noqa: F401
            ai_config, analytics, conversation, knowledge, memory, settings as settings_model, tool, user
        )

        # Create tables using raw SQL with IF NOT EXISTS for idempotency
        from app.models import (  # noqa: F401
            ai_config, analytics, conversation, knowledge, memory, settings as settings_model, tool, user
        )
        async with engine.connect() as conn:
            # Get DDL statements from metadata
            from sqlalchemy.schema import CreateTable
            for table in Base.metadata.sorted_tables:
                # Use raw DDL to create tables with proper IF NOT EXISTS handling
                ddl_str = str(CreateTable(table).compile(bind=engine))
                # Modify to add IF NOT EXISTS
                ddl_str = ddl_str.replace("CREATE TABLE ", "CREATE TABLE IF NOT EXISTS ")
                try:
                    await conn.execute(text(ddl_str))
                    await conn.commit()
                except Exception:
                    # If table creation fails, it might already exist
                    pass
        logger.info("database.tables_initialized")

    except Exception as exc:
        logger.error("database.connection_failed", error=str(exc))
        raise


async def disconnect_db() -> None:
    """Called at application shutdown: dispose the connection pool."""
    await engine.dispose()
    logger.info("database.disconnected")


async def connect_redis() -> None:
    """Verify Redis is reachable at startup."""
    client = get_redis()
    try:
        await client.ping()
        logger.info("redis.connected", url=settings.redis_url)
    except Exception as exc:
        logger.error("redis.connection_failed", error=str(exc))
        raise
    finally:
        await client.aclose()


async def disconnect_redis() -> None:
    """Close the shared Redis connection pool."""
    global _redis_pool
    if _redis_pool is not None:
        await _redis_pool.aclose()
        _redis_pool = None
    logger.info("redis.disconnected")
